#!/bin/bash
ssh-keygen -t rsa -b 4096 -f "./ssh/id_rsa" -N ""
# file generated by this script should be added (public key - id_rsa.pub) to Deploy Key in githubie (zainstalowanie Deploy Key) 
# More about Deploy Keys:
# https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys
# https://developer.github.com/v3/guides/managing-deploy-keys/
#file:
#./id_rsa
#key:
#empty